"""Inspect a RAIQ checkpoint without modifying it.

Use only with checkpoints generated by a trusted RAIQ training run. The report is
intended as an evidence record before attempting a checkpoint-resume test.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import torch
from torch.torch_version import TorchVersion


def _state_tensor_count(state: dict[str, Any]) -> int:
    """Return the number of tensors in a serialized state mapping."""

    return sum(1 for value in state.values() if isinstance(value, torch.Tensor))


def inspect_checkpoint(path: Path) -> dict[str, Any]:
    """Return a JSON-safe read-only verification report for a RAIQ checkpoint."""

    checkpoint = path.resolve()
    if not checkpoint.is_file():
        raise FileNotFoundError(f"checkpoint does not exist: {checkpoint}")
    with torch.serialization.safe_globals([TorchVersion]):
        payload = torch.load(checkpoint, map_location="cpu", weights_only=True)
    if not isinstance(payload, dict):
        raise ValueError("checkpoint payload must be a mapping")

    model_state = payload.get("model_state")
    optimizer_state = payload.get("optimizer_state")
    run_config = payload.get("run_config")
    rng_state = payload.get("rng_state")
    scaler_state = payload.get("scaler_state")
    optimizer_groups = (
        optimizer_state.get("param_groups", []) if isinstance(optimizer_state, dict) else []
    )
    optimizer_slots = optimizer_state.get("state", {}) if isinstance(optimizer_state, dict) else {}
    training_config = run_config.get("training", {}) if isinstance(run_config, dict) else {}
    scaler_expected = (
        training_config.get("device") == "cuda"
        and training_config.get("dtype") == "float16"
    )

    report = {
        "checkpoint": str(checkpoint),
        "checkpoint_size_bytes": checkpoint.stat().st_size,
        "format_version": payload.get("format_version"),
        "recorded_step": payload.get("step"),
        "model_state": {
            "present": isinstance(model_state, dict),
            "tensor_count": _state_tensor_count(model_state) if isinstance(model_state, dict) else 0,
        },
        "optimizer_state": {
            "present": isinstance(optimizer_state, dict),
            "parameter_group_count": len(optimizer_groups),
            "parameter_state_entry_count": len(optimizer_slots),
        },
        "training_state": {
            "run_config_present": isinstance(run_config, dict),
            "rng_state_present": isinstance(rng_state, dict),
            "python_rng_present": isinstance(rng_state, dict) and "python" in rng_state,
            "torch_cpu_rng_present": isinstance(rng_state, dict) and "torch_cpu" in rng_state,
            "torch_cuda_rng_present": isinstance(rng_state, dict) and "torch_cuda" in rng_state,
            "scheduler_state": "stateless warmup-cosine schedule reconstructs from run_config and recorded_step",
        },
        "grad_scaler_state": {
            "expected": scaler_expected,
            "present": isinstance(scaler_state, dict),
            "scale": None if not isinstance(scaler_state, dict) else scaler_state.get("scale"),
        },
    }
    report["passed"] = all(
        (
            isinstance(report["recorded_step"], int),
            report["recorded_step"] >= 0,
            report["model_state"]["present"],
            report["model_state"]["tensor_count"] > 0,
            report["optimizer_state"]["present"],
            report["optimizer_state"]["parameter_group_count"] > 0,
            report["training_state"]["run_config_present"],
            report["training_state"]["rng_state_present"],
            not report["grad_scaler_state"]["expected"]
            or report["grad_scaler_state"]["present"],
        )
    )
    return report


def main() -> None:
    parser = argparse.ArgumentParser(description="Inspect a trusted RAIQ training checkpoint")
    parser.add_argument("--checkpoint", required=True, help="Path to checkpoint_last.pt")
    parser.add_argument("--output", default=None, help="Optional JSON report path")
    args = parser.parse_args()
    report = inspect_checkpoint(Path(args.checkpoint))
    rendered = json.dumps(report, indent=2, sort_keys=True)
    if args.output is not None:
        Path(args.output).write_text(rendered + "\n", encoding="utf-8")
    print(rendered)
    if not report["passed"]:
        raise SystemExit(2)


if __name__ == "__main__":
    main()
